version: '3'
services:
  ui:
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - frontend
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3333:3333'
    networks:
      - backend
      - frontend
  db:
    image: 'mysql'
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
