version: '3'
services:
  mydogs-ui:
    build: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - mydogs-api
  mydogs-api:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    ports:
      - 3333:3333
    networks:
      - backend
      - frontend
  db:
    image: 'mysql'
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'database'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
